apiVersion: V1
kind: replicationController
metadata:
  name: myjenkins-rc
spec:
   replicas: 3
   selector:
     app: myjenkins-pod
   template:
     metadata:
       labels:
          app: myjenkins-pod
     spec:
        containers:
        - name: myjenkins-container
          image: jenkins:2.60.3
          ports:
          - containersPort: 8080
