apiVersion: v1
kind: Service
metadata:
  name: myjenkins-svc
  labels:
     app: myjenkins-pod
spec:
  type: nodeport
  ports:
  - port: 8080 
    nodeport: 30001
    protocol: TCP 
  selector: 
      app: myjekins-pod 